package com.ilizma.personal.view.utils

const val LOADING_TAG = "loading"
const val PERSONAL_IMAGE_TAG = "personal_image"
const val PERSONAL_NAME_TAG = "personal_name"
const val PERSONAL_SURNAME_TAG = "personal_surname"
const val PERSONAL_SURNAME2_TAG = "personal_surname2"
const val PERSONAL_PHONE_TAG = "personal_phone"
const val PERSONAL_EMAIL_TAG = "personal_email"
const val PERSONAL_ADDRESS_TAG = "personal_address"
const val PERSONAL_CITY_TAG = "personal_city"
const val PERSONAL_POSTAL_CODE_TAG = "personal_postal_code"
const val PERSONAL_BORN_DATE_TAG = "personal_born_date"
const val PERSONAL_SKILLS_TAG = "personal_skills"
const val PERSONAL_DESCRIPTION_TAG = "personal_description"
const val PERSONAL_OTHER_TITLE_TAG = "personal_other_title"
const val PERSONAL_OTHER_DESCRIPTION_TAG = "personal_other_description"
const val PERSONAL_OTHER_LINK_TAG = "personal_other_link"
const val ERROR_TAG = "error"